name: Update Stats

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering
    inputs:
      manualTrigger:
        description: 'Trigger the workflow manually'
        required: false
        default: 'true'  # You can adjust default value if needed

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          echo "requests" > requirements.txt
          pip install -r requirements.txt
      
      - name: Update mods count
        run: python count-mods.py
        working-directory: .github/scripts

      - name: Update packages count
        run: python count-packages.py
        working-directory: .github/scripts
