name: Count Packages and Generate Badge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  count-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: python -m pip install --upgrade pip requests

    - name: Count packages and generate badge
      run: python count_packages.py

    - name: Upload badge to repository
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add Badges/package_count_badge.json
        git commit -m 'Update package count badge'
        git push
